language: clojure
lein: lein2
before_script:
  - psql -c 'create database test;' -U postgres
script: TEST_DATABASE_URL=postgres://postgres:@localhost:5432/test lein2 with-profile dev test
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
